export const teamsData = [
  {
    teamName: "Kiren",
    players: [
      {
        name: "Hashmatullah Shahidi (AFG)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "MA Starc (AUS)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "A Zampa (AUS)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "JM Bairstow (ENG)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "HH Pandya (IND)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "SS Iyer (IND)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "V Kohli (IND)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "TA Boult (NZ)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "DJ Mitchell (NZ)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "Babar Azam (PAK)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "BKG Mendis (SL)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "Theekshana",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "MJ Henry (NZ)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "Ibrahim Zadran (AFG)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "KA Maharaj (SA)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
    ],
  },
  {
    teamName: "Dinesh",
    players: [
      {
        name: "Rashid Khan (AFG)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "JR Hazlewood (AUS)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "Litton Das (BAN)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "Mehidy Hasan Miraz (BAN)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "DJ Malan (ENG)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "RG Sharma (IND)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "JJ Bumrah (IND)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "DP Conway (NZ)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "Imam-ul-Haq (PAK)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "Fakhar Zaman (PAK)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "Q de Kock (SA)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "M Jansen (SA)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "P Nissanka (SL)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "Fazalhaq Farooqi (AFG)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "MDKJ Perera (SL)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
    ],
  },
  {
    teamName: "Shashank",
    players: [
      {
        name: "M Labuschagne (AUS)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "Najmul Hossain Shanto (BAN)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "JC Buttler (ENG)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "SM Curran (ENG)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "LS Livingstone (ENG)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "JE Root (ENG)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "MA Wood (ENG)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "Shubhman Gill (IND)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "Mohammed Siraj (IND)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "Kuldeep Yadav (IND)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "MS Chapman (NZ)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "Haris Rauf (PAK)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "AK Markram (SA)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "HE van der Dussen (SA)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "SK Yadav (IND)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
    ],
  },
  {
    teamName: "Vasikaran",
    players: [
      {
        name: "Noor Ahmed (AFG)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "Naveen-ul-Haq (AFG)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "PJ Cummins (AUS)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "SPD Smith (AUS)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "Ben Stokes (ENG)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "Ishan Kishan (IND)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "KL Rahul (IND)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "TWM Latham (NZ)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "MJ Santner (NZ)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "Shaheen Shah Afridi (PAK)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "Mohammad Rizwan (PAK)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "DA Miller (SA)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "MD Shanaka (SL)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "S Samarawickrama (SL)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "DN Wellalage (SL)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "Abdullah Shafique (PAK)",
        runs: -133,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
    ],
  },

  {
    teamName: "Yeshwant and Siddharth",
    players: [
      {
        name: "Rahmanullah Gurbaz (AFG)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "C Green (AUS)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "Shakib Al Hasan (BAN)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "Hridoy",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "Mahmudullah",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "MM Ali (ENG)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "AU Rashid (ENG)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "CR Woakes (ENG)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "R Ashwin (IND)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "RA Jadeja (IND)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "Thakur",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "CN Ackermann (NED)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "LV van Beek (NED)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "KS Williamson (NZ)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "H Klaasen (SA)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
    ],
  },
  {
    teamName: "Roshan and Naveen",
    players: [
      {
        name: "Mohammad Nabi (AFG)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "Mujeeb Ur Rahman (AFG)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "MR Marsh (AUS)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "GJ Maxwell (AUS)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "DA Warner (AUS)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "Mustafizur Rahman (BAN)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "Shami",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "BFW de Leede (NED)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "R Ravindra (NZ)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "Sodhi",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "Shadab Khan (PAK)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "Mushfiqur Rahim (BAN)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "K Rabada (SA)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "DM de Silva (SL)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
      {
        name: "M Pathirana (SL)",
        runs: 0,
        wickets: 0,
        battingPoints: 0,
        bowlingPoints: 0,
        totalPoints: 0,
      },
    ],
  },
];
